apiVersion: v1
kind: Service
metadata:
  name: workf
  namespace: namespace-workflow-1738684628456
  labels:
    app.kubernetes.io/name: workf
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: workf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000